### ISSUE TITLE
Error while running chemage

### ISSUE THREAD

**Issue by sankha-das** [marcoalopez/chemical_age_script#1]
Afetr installing python in my windows 32 bit system, I am getting an error message when I am running the chemage script. The error message says "no six module". I have installed python 2.7.4. Please help.
_Traceback (most recent call last):
  File "C:\Users\Sankha Das\Desktop\chemical_age_script-1.1.1\chemical_age_script-1.1.1\find_chemage.py", line 36, in <module>
    import matplotlib.pyplot as plt
  File "C:\Python27\lib\site-packages\matplotlib\__init__.py", line 105, in <module>
    import six
ImportError: No module named six
>>>_

**Comment by marcoalopez** [comment]
Hi Sankha, it seems to me that you have a problem with your matplotlib installation (required for the plots). Indeed, I am not able to reproduce your issue on my machine (although I have to say I no longer use Python 2.7+ versions to test bugs but 3.5+). My advice is to reinstall matplotlib or your Python distribution. I recommend you installing the Anaconda or the Enthought Canopy distributions, since both distributions have free basic versions that include all the scientific packages required by the script. I drop you the links below:
https://www.anaconda.com/download/
https://www.enthought.com/products/canopy/

if you have a limited space in your hard disk try:
http://conda.pydata.org/miniconda.html
although in this case you will have to install manually matplotlib, numpy or other required dependencies using "conda install matplotlib" and so on...

All the best,
Marco

**Comment by sankha-das** [comment]
Sir,
       Thank you for your suggestion. Now it is working.
I have another quarry; for find_chemage_array  should  the data format be
(all Th values, All U values, All Pb values)? Please clarify.

With Regards,
Sankha

**Comment by marcoalopez** [comment]
Hi Sankha,

Yes if you store your results as Python lists, for example:

Th_values = [3116, 8456, 5075, 5032]
U_values = [3585, 3899, 3716, 3652]
Pb_values = [256, 535, 198, 269]

then use the find_chemage_array function as follows:

find_chemage_array(Th_values, U_values, Pb_values)

that's it.

Cheers, Marco

**Comment by sankha-das** [comment]
Thank you sir
